stages:
  - build

variables:
  CONTAINER_IMAGE: ergw/vpp_test
  CONTAINER_IMAGE_BUILT: ${CONTAINER_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}
  CONTAINER_IMAGE_LATEST: ${CONTAINER_IMAGE}:latest
  CI_REGISTRY: https://index.docker.io/v1/  # container registry URL

# build container image
build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - echo "Building Dockerfile-based application..."
    - docker build -t ${CONTAINER_IMAGE_BUILT} .
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - echo "Pushing to the Container Registry      ${CONTAINER_IMAGE_BUILT}"
    - docker push ${CONTAINER_IMAGE_BUILT}
